import type { Metadata } from "next";
import "./globals.css";
import { fontRoboto } from "@/config/font";
import clsx from "clsx";
import Navbar from "@/components/shared/navbar";
import LeftNav from "@/components/shared/left-nav";
import BottomBar from "@/components/shared/bottom-bar";
import RightBar from "@/components/shared/right-bar";
import { Toaster } from "sonner";
import { SwiperProvider } from "@/utils/use-swiper-context";

export const metadata: Metadata = {
  title: "Pheonix Collective",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <SwiperProvider>
        <body
          className={clsx(
            "w-full h-screen font-roboto antialiased bg-center bg-contain bg-no-repeat",
            fontRoboto.variable
          )}
          style={{
            background: "url('/assets/images/main-bg.svg')",
            backgroundPosition: "center",
            backgroundSize: "cover",
            backgroundRepeat: "no-repeat",
          }}
        >
          <Toaster />
          <div className="absolute inset-0 pointer-events-none z-10">
            <video
              className="w-full h-full object-cover opacity-50 mix-blend-overlay"
              style={{
                filter: "hue-rotate(30deg) brightness(0.9) saturate(0.8)",
              }}
              autoPlay
              loop
              muted
              playsInline
            >
              <source src="/assets/overlay-video.mp4" type="video/mp4" />
            </video>
          </div>

          <Navbar />

          <div className="hidden md:block relative w-20 h-screen z-40">
            <LeftNav />
          </div>
          <RightBar />
          <BottomBar />

          {children}
        </body>
      </SwiperProvider>
    </html>
  );
}
